/*
 * Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// GENERATED by lms/dart/tool/sync_team_assets.dart - do not edit.
// The team assets the SDK ships into the shell's public/team/ (the
// same consumable set the Dart half vendors into assets/team/: tutor,
// assistant, founder and onboarding renders plus any audio/video; never
// marketing collateral), grouped by persona and listed as the URL the
// composed shell serves each file at. Regenerated on every lms/team/**
// push by .github/workflows/sync_team_assets.yml.

/** Persona folder (relative to lms/team, e.g. `tutors/CAPS/tutor_001`) -> the files it ships. */
export const TEAM_ASSETS: Readonly<Record<string, readonly string[]>> = {
  "assistants/CAPS/assistant_001": [
    "/team/assistants/CAPS/assistant_001/appearance/renders/avatar_168.webp",
    "/team/assistants/CAPS/assistant_001/appearance/renders/avatar_512.webp",
    "/team/assistants/CAPS/assistant_001/appearance/renders/card_1080x1440.webp",
  ],
  "assistants/CAPS/assistant_002": [
    "/team/assistants/CAPS/assistant_002/appearance/renders/avatar_168.webp",
    "/team/assistants/CAPS/assistant_002/appearance/renders/avatar_512.webp",
    "/team/assistants/CAPS/assistant_002/appearance/renders/card_1080x1440.webp",
  ],
  "assistants/CAPS/assistant_003": [
    "/team/assistants/CAPS/assistant_003/appearance/renders/avatar_168.webp",
    "/team/assistants/CAPS/assistant_003/appearance/renders/avatar_512.webp",
    "/team/assistants/CAPS/assistant_003/appearance/renders/card_1080x1440.webp",
  ],
  "founders/Ray_Thompson": [
    "/team/founders/Ray_Thompson/appearance/renders/avatar_168.webp",
    "/team/founders/Ray_Thompson/appearance/renders/avatar_512.webp",
    "/team/founders/Ray_Thompson/appearance/renders/card_1080x1440.webp",
  ],
  "onboarding/students/renders/01_welcome_1_live_classes": [
    "/team/onboarding/students/renders/01_welcome_1_live_classes/card_1080x1350.webp",
    "/team/onboarding/students/renders/01_welcome_1_live_classes/slide_1080x1920.webp",
  ],
  "onboarding/students/renders/02_welcome_2_know_where_you_stand": [
    "/team/onboarding/students/renders/02_welcome_2_know_where_you_stand/card_1080x1350.webp",
    "/team/onboarding/students/renders/02_welcome_2_know_where_you_stand/slide_1080x1920.webp",
  ],
  "onboarding/students/renders/03_welcome_3_library_stays_yours": [
    "/team/onboarding/students/renders/03_welcome_3_library_stays_yours/card_1080x1350.webp",
    "/team/onboarding/students/renders/03_welcome_3_library_stays_yours/slide_1080x1920.webp",
  ],
  "onboarding/students/renders/04_role_choice_student": [
    "/team/onboarding/students/renders/04_role_choice_student/card_1080x1350.webp",
    "/team/onboarding/students/renders/04_role_choice_student/slide_1080x1920.webp",
  ],
  "onboarding/students/renders/05_grade_capture": [
    "/team/onboarding/students/renders/05_grade_capture/card_1080x1350.webp",
    "/team/onboarding/students/renders/05_grade_capture/slide_1080x1920.webp",
  ],
  "tutors/CAPS/tutor_001": [
    "/team/tutors/CAPS/tutor_001/appearance/renders/avatar_168.webp",
    "/team/tutors/CAPS/tutor_001/appearance/renders/avatar_512.webp",
    "/team/tutors/CAPS/tutor_001/appearance/renders/card_1080x1440.webp",
  ],
  "tutors/CAPS/tutor_002": [
    "/team/tutors/CAPS/tutor_002/appearance/renders/avatar_168.webp",
    "/team/tutors/CAPS/tutor_002/appearance/renders/avatar_512.webp",
    "/team/tutors/CAPS/tutor_002/appearance/renders/card_1080x1440.webp",
  ],
  "tutors/CAPS/tutor_003": [
    "/team/tutors/CAPS/tutor_003/appearance/renders/avatar_168.webp",
    "/team/tutors/CAPS/tutor_003/appearance/renders/avatar_512.webp",
    "/team/tutors/CAPS/tutor_003/appearance/renders/card_1080x1440.webp",
  ],
  "tutors/CAPS/tutor_004": [
    "/team/tutors/CAPS/tutor_004/appearance/renders/avatar_168.webp",
    "/team/tutors/CAPS/tutor_004/appearance/renders/avatar_512.webp",
    "/team/tutors/CAPS/tutor_004/appearance/renders/card_1080x1440.webp",
  ],
  "tutors/CAPS/tutor_005": [
    "/team/tutors/CAPS/tutor_005/appearance/renders/avatar_168.webp",
    "/team/tutors/CAPS/tutor_005/appearance/renders/avatar_512.webp",
    "/team/tutors/CAPS/tutor_005/appearance/renders/card_1080x1440.webp",
  ],
  "tutors/CAPS/tutor_006": [
    "/team/tutors/CAPS/tutor_006/appearance/renders/avatar_168.webp",
    "/team/tutors/CAPS/tutor_006/appearance/renders/avatar_512.webp",
    "/team/tutors/CAPS/tutor_006/appearance/renders/card_1080x1440.webp",
  ],
  "tutors/CAPS/tutor_007": [
    "/team/tutors/CAPS/tutor_007/appearance/renders/avatar_168.webp",
    "/team/tutors/CAPS/tutor_007/appearance/renders/avatar_512.webp",
    "/team/tutors/CAPS/tutor_007/appearance/renders/card_1080x1440.webp",
  ],
  "tutors/CAPS/tutor_008": [
    "/team/tutors/CAPS/tutor_008/appearance/renders/avatar_168.webp",
    "/team/tutors/CAPS/tutor_008/appearance/renders/avatar_512.webp",
    "/team/tutors/CAPS/tutor_008/appearance/renders/card_1080x1440.webp",
  ],
  "tutors/CAPS/tutor_009": [
    "/team/tutors/CAPS/tutor_009/appearance/renders/avatar_168.webp",
    "/team/tutors/CAPS/tutor_009/appearance/renders/avatar_512.webp",
    "/team/tutors/CAPS/tutor_009/appearance/renders/card_1080x1440.webp",
  ],
  "tutors/CAPS/tutor_010": [
    "/team/tutors/CAPS/tutor_010/appearance/renders/avatar_168.webp",
    "/team/tutors/CAPS/tutor_010/appearance/renders/avatar_512.webp",
    "/team/tutors/CAPS/tutor_010/appearance/renders/card_1080x1440.webp",
  ],
  "tutors/CAPS/tutor_011": [
    "/team/tutors/CAPS/tutor_011/appearance/renders/avatar_168.webp",
    "/team/tutors/CAPS/tutor_011/appearance/renders/avatar_512.webp",
    "/team/tutors/CAPS/tutor_011/appearance/renders/card_1080x1440.webp",
  ],
  "tutors/CAPS/tutor_012": [
    "/team/tutors/CAPS/tutor_012/appearance/renders/avatar_168.webp",
    "/team/tutors/CAPS/tutor_012/appearance/renders/avatar_512.webp",
    "/team/tutors/CAPS/tutor_012/appearance/renders/card_1080x1440.webp",
  ],
};

/** Every file a persona ships, by its folder key or by its last path segment (`tutor_001`). */
export function teamAssetsFor(slug: string): readonly string[] {
  const direct = TEAM_ASSETS[slug];
  if (direct) return direct;
  const key = Object.keys(TEAM_ASSETS).find((k) => k.endsWith(`/${slug}`));
  return key ? TEAM_ASSETS[key] : [];
}

/**
 * The image a card should show for a persona: the named rendition when it
 * ships (`card_1080x1440.webp` is the 3:4 portrait TutorCard draws full-bleed),
 * else the first image the persona has, else undefined (the card falls
 * back to initials, as the Flutter card does).
 */
export function teamImageFor(
  slug: string,
  preferred = "card_1080x1440.webp",
): string | undefined {
  const files = teamAssetsFor(slug);
  return (
    files.find((f) => f.endsWith(`/${preferred}`)) ??
    files.find((f) => /\.(webp|png|jpe?g|avif|gif)$/i.test(f))
  );
}
