/*
 * Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

"use client";

// The landing page's tutor roster: every tutor as the app's flip card
// (landing/lms-tutor-card.tsx - portrait front, bio and "Start with" back),
// then the session assistants as the same card. Copy:
// LMS_LANDING_CONFIG.tutors; portraits: the team renders this SDK ships
// into public/team/ (landing/team-assets.ts, generated by
// lms/dart/tool/sync_team_assets.dart).
//
// Two rows, one per width, and the card is the same in both:
//
//   * from 640px up the roster KEEPS SCROLLING, the way the testimonials do
//     (Ray, 2026-09-09: "tutor cards should keep scrolling like
//     testamonials"): landing/lms-marquee.tsx, the same row base_sdk's
//     testimonials marquee runs - the same keyframes, the same pause under
//     the pointer, the same edge fades, the same stillness under
//     prefers-reduced-motion - over these cards. The row is full-bleed,
//     as the testimonials' is, and it slows to the testimonials' own pace.
//     The assistants' row is the same marquee, and since three cards fit a
//     wide screen it stands still and centred there, moving only where it
//     overflows;
//   * below 640px the roster is still the DECK (Ray, 2026-09-08: "the
//     tutor cards can still be a deck that take one row and can be swipped
//     like in dart"): one row you swipe, the next card's edge always
//     showing, exactly one card per swipe, position dots under it -
//     lms/dart's CardDeck as landing/lms-card-deck.tsx renders it for the
//     web. Unchanged from 1.3.0, to the class.
//
// A visitor who asked for reduced motion gets the deck at every width: a
// still row scrolled by hand is what the marquee's own reduced-motion rule
// promises, and the deck is that row with arrows, dots and keys.
//
// The two rows are both in the DOM and the breakpoint picks one, so the
// server sends the right row for the width and nothing shifts on
// hydration; the portraits are the same URLs in both, fetched once.

import React from "react";

import { LmsCardDeck } from "@/components/custom/landing/lms-card-deck";
import { useMediaQuery } from "@/components/custom/landing/lms-flip-card";
import {
  LMS_LANDING_CONFIG,
  type DeckLabels,
} from "@/components/custom/landing/lms-landing-config";
import { LmsMarquee } from "@/components/custom/landing/lms-marquee";
import { LmsTutorCard } from "@/components/custom/landing/lms-tutor-card";
import type {
  PageSectionMeta,
  PageSectionProps,
} from "@/components/custom/landing/page-sections";

/** The section's own column: the deck sits in it, the marquee bleeds past it. */
const CONTAINER = "container mx-auto px-4 xl:px-0 max-w-6xl";

/**
 * One roster row: the deck on a phone or under reduced motion, the marquee
 * from 640px up. The cards arrive as children, drawn once and handed to
 * both rows. Both wrappers are `w-full`: the assistants' row sits in a
 * centred column, and a frame that shrank to its cards could never be
 * narrower than them, so it would never know it overflowed.
 */
function Roster({
  labels,
  deckClassName,
  deckWrapClassName,
  children,
}: {
  labels: DeckLabels;
  deckClassName?: string;
  deckWrapClassName?: string;
  children: React.ReactNode;
}) {
  const stillness = useMediaQuery("(prefers-reduced-motion: reduce)");

  const deck = (
    <div className={CONTAINER}>
      <LmsCardDeck
        labels={labels}
        deckClassName={deckClassName}
        className={deckWrapClassName}
      >
        {children}
      </LmsCardDeck>
    </div>
  );

  if (stillness) return deck;

  return (
    <>
      <div className="w-full sm:hidden">{deck}</div>
      <div className="hidden w-full sm:block">
        <LmsMarquee label={labels.label} itemClassName="sc-marquee-slot">
          {children}
        </LmsMarquee>
      </div>
    </>
  );
}

export function LmsTutorsSection({
  id,
  signupUrl = "/register",
}: {
  id?: string;
  signupUrl?: string;
}) {
  const config = LMS_LANDING_CONFIG.tutors;
  if (!config || config.tutors.length === 0) return null;

  return (
    <section
      id={id}
      className="w-full bg-[var(--sc-card-alt)] py-16 md:py-24 border-y border-[var(--sc-stroke-subtle)]"
    >
      <div className={`${CONTAINER} flex flex-col items-center text-center gap-5`}>
        <p className="sc-eyebrow">
          {config.eyebrow}
        </p>
        <h2 className="text-[32px] md:text-[48px] font-extrabold leading-[1.1] tracking-tight text-[var(--sc-ink)] text-balance">
          {config.heading}
        </h2>
        <p className="text-lg md:text-xl font-medium text-[var(--sc-ink-2)] max-w-2xl">
          {config.blurb}
        </p>
      </div>

      <div className="mt-12">
        <Roster labels={config.deck}>
          {config.tutors.map((tutor, index) => (
            <LmsTutorCard
              key={tutor.slug ?? tutor.name}
              persona={tutor}
              role="tutor"
              signupUrl={signupUrl}
              priority={index < 4}
            />
          ))}
        </Roster>
      </div>

      {config.assistants.length > 0 && (
        <div className="mt-12 flex flex-col items-center gap-6">
          <div className={`${CONTAINER} flex flex-col items-center border-t border-[var(--sc-stroke-subtle)] pt-10`}>
            <h3 className="text-lg font-bold text-[var(--sc-ink)]">
              {config.assistantsHeading}
            </h3>
          </div>
          <Roster
            labels={config.assistantsDeck}
            deckWrapClassName="w-full lg:max-w-3xl"
            /* Three of them: two across with the third's edge showing,
               then all three at once with nothing left to swipe to. */
            deckClassName="sc-deck-trio"
          >
            {config.assistants.map((assistant) => (
              <LmsTutorCard
                key={assistant.slug ?? assistant.name}
                persona={assistant}
                role="assistant"
                signupUrl={signupUrl}
              />
            ))}
          </Roster>
        </div>
      )}
    </section>
  );
}

/**
 * What this section adds to base_sdk's landing host when registered in
 * components/custom/landing/page-sections.ts: its place in the page order
 * and its floating-nav entry.
 */
export const meta: PageSectionMeta = {
  order: 30,
  nav: [{ id: "tutors", label: "Tutors" }],
};

/** The registered form: the page's sign-up URL feeds the cards' "Start with" action. */
export default function LmsTutorsPageSection({ id, signupUrl }: PageSectionProps) {
  return <LmsTutorsSection id={id} signupUrl={signupUrl} />;
}
