/*
 * Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

"use client";

// The landing page's tutor deck: every tutor on the roster as the app's
// flip card (landing/lms-tutor-card.tsx - portrait front, bio and "Start
// with" back), then the session assistants as the same card. Copy:
// LMS_LANDING_CONFIG.tutors; portraits: the team renders this SDK ships
// into public/team/ (landing/team-assets.ts, generated by
// lms/dart/tool/sync_team_assets.dart).

import React from "react";

import { LMS_LANDING_CONFIG } from "@/components/custom/landing/lms-landing-config";
import { LmsTutorCard } from "@/components/custom/landing/lms-tutor-card";
import type {
  PageSectionMeta,
  PageSectionProps,
} from "@/components/custom/landing/page-sections";

export function LmsTutorsSection({
  id,
  signupUrl = "/register",
}: {
  id?: string;
  signupUrl?: string;
}) {
  const config = LMS_LANDING_CONFIG.tutors;
  if (!config || config.tutors.length === 0) return null;

  return (
    <section
      id={id}
      className="w-full bg-[var(--sc-card-alt)] py-16 md:py-24 border-y border-[var(--sc-stroke-subtle)]"
    >
      <div className="container mx-auto px-4 xl:px-0 max-w-6xl flex flex-col gap-12">
        <div className="flex flex-col items-center text-center gap-5">
          <p className="sc-eyebrow">
            {config.eyebrow}
          </p>
          <h2 className="text-[32px] md:text-[48px] font-extrabold leading-[1.1] tracking-tight text-[var(--sc-ink)] text-balance">
            {config.heading}
          </h2>
          <p className="text-lg md:text-xl font-medium text-[var(--sc-ink-2)] max-w-2xl">
            {config.blurb}
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
          {config.tutors.map((tutor, index) => (
            <LmsTutorCard
              key={tutor.slug ?? tutor.name}
              persona={tutor}
              role="tutor"
              signupUrl={signupUrl}
              priority={index < 4}
            />
          ))}
        </div>

        {config.assistants.length > 0 && (
          <div className="flex flex-col items-center gap-6 border-t border-[var(--sc-stroke-subtle)] pt-10">
            <h3 className="text-lg font-bold text-[var(--sc-ink)]">
              {config.assistantsHeading}
            </h3>
            <div className="grid w-full grid-cols-1 sm:grid-cols-3 gap-4 lg:max-w-3xl">
              {config.assistants.map((assistant) => (
                <LmsTutorCard
                  key={assistant.slug ?? assistant.name}
                  persona={assistant}
                  role="assistant"
                  signupUrl={signupUrl}
                />
              ))}
            </div>
          </div>
        )}
      </div>
    </section>
  );
}

/**
 * What this section adds to base_sdk's landing host when registered in
 * components/custom/landing/page-sections.ts: its place in the page order
 * and its floating-nav entry.
 */
export const meta: PageSectionMeta = {
  order: 30,
  nav: [{ id: "tutors", label: "Tutors" }],
};

/** The registered form: the page's sign-up URL feeds the cards' "Start with" action. */
export default function LmsTutorsPageSection({ id, signupUrl }: PageSectionProps) {
  return <LmsTutorsSection id={id} signupUrl={signupUrl} />;
}
